# -*- coding: utf-8 -*-
"""Full bilingual OpenAPI 3.1 catalog for all 196 Aliasarr REST API endpoints.
Provides 100% Russian and 100% English summaries, descriptions, parameters, and responses.
"""
from __future__ import annotations

# Mapping: (path, method) -> (ru_summary, en_summary, ru_description, en_description)
ENDPOINT_CATALOG: dict[tuple[str, str], tuple[str, str, str, str]] = {
    ('/', 'GET'): (
        'Главная страница веб-интерфейса Aliasarr',
        'Aliasarr web UI home page',
        'Отдает главную страницу SPA веб-интерфейса системы Aliasarr.',
        'Serves the primary single-page application (SPA) web interface for Aliasarr.',
    ),
    ('/api/docs', 'GET'): (
        'Интерактивный справочник REST API (Swagger UI)',
        'Interactive REST API Reference (Swagger UI)',
        'Отображает интерактивный веб-интерфейс Swagger UI для тестирования и изучения всех методов REST API.',
        'Renders the interactive Swagger UI web interface for inspecting and testing all REST API operations.',
    ),
    ('/api/docs.html', 'GET'): (
        'Справочник REST API (прямая ссылка)',
        'REST API Reference (direct URL)',
        'Прямая ссылка на страницу интерактивного справочника Swagger UI.',
        'Direct URL serving the interactive Swagger UI API reference page.',
    ),
    ('/api/v1/audit', 'GET'): (
        'Получить журнал аудита действий',
        'Get security audit logs',
        'Возвращает записи журнала аудита безопасности с поддержкой фильтрации по пользователю, диапазону дат и типу события.',
        'Returns security audit trail records with filtering by user, date range, and action type.',
    ),
    ('/api/v1/audit/clear', 'POST'): (
        'Очистить журнал аудита',
        'Clear security audit logs',
        'Полностью удаляет все исторические записи из журнала аудита безопасности.',
        'Permanently purges all historical entries from the security audit event log.',
    ),
    ('/api/v1/auth/2fa/confirm', 'POST'): (
        'Подтвердить активацию 2FA',
        'Confirm two-factor authentication setup',
        'Проверяет введенный проверочный код и окончательно активирует 2FA для профиля.',
        'Validates the verification passcode and permanently enables 2FA on the user account.',
    ),
    ('/api/v1/auth/2fa/disable', 'POST'): (
        'Отключить двухфакторную аутентификацию',
        'Disable two-factor authentication',
        'Отключает защиту 2FA для профиля после подтверждения действующим паролем.',
        'Disables two-factor authentication on the account after password confirmation.',
    ),
    ('/api/v1/auth/2fa/setup', 'POST'): (
        'Инициализировать настройку 2FA',
        'Initialize two-factor authentication setup',
        'Генерирует секретный ключ TOTP и URI для добавления в приложение аутентификатора.',
        'Generates a new TOTP secret key and QR code URI for authenticator applications.',
    ),
    ('/api/v1/auth/change-password', 'POST'): (
        'Сменить пароль учетной записи',
        'Change account password',
        'Выполняет смену пароля текущего пользователя с валидацией прежнего пароля.',
        'Changes account password for the current user after validating current password.',
    ),
    ('/api/v1/auth/credentials', 'PUT'): (
        'Обновить логин или пароль',
        'Update user credentials',
        'Изменяет учетные данные пользователя с обязательной проверкой действующего пароля.',
        'Updates user account credentials after verifying the existing current password.',
    ),
    ('/api/v1/auth/login', 'POST'): (
        'Авторизация по логину и паролю',
        'Authenticate user with credentials',
        'Выполняет вход пользователя в систему с выдачей защищенного сессионного cookie или запросом 2FA-кода.',
        'Authenticates a user via credentials, issuing a secure session cookie or initiating a 2FA TOTP challenge.',
    ),
    ('/api/v1/auth/login-2fa', 'POST'): (
        'Подтверждение входа через 2FA TOTP',
        'Verify 2FA TOTP passcode during login',
        'Проверяет одноразовый пароль TOTP в процессе двухфакторной аутентификации и завершает вход.',
        'Validates the one-time TOTP passcode during two-factor authentication and completes the login process.',
    ),
    ('/api/v1/auth/logout', 'POST'): (
        'Завершить текущую сессию',
        'Logout current user session',
        'Завершает сеанс пользователя и аннулирует авторизационный сессионный cookie.',
        'Terminates the active user session and invalidates the authentication session cookie.',
    ),
    ('/api/v1/auth/me', 'GET'): (
        'Профиль текущего пользователя',
        'Get current user profile',
        'Возвращает учетные данные, права доступа (RBAC), аватар и персональный ключ авторизованного пользователя.',
        'Returns account details, RBAC permissions, avatar, and personal API key of the logged-in user.',
    ),
    ('/api/v1/auth/me', 'PUT'): (
        'Обновить профиль текущего пользователя',
        'Update current user profile',
        'Позволяет авторизованному пользователю обновить имя, email или язык интерфейса в своем профиле.',
        'Allows the logged-in user to update username, email, or preferred interface language.',
    ),
    ('/api/v1/auth/me/avatar', 'POST'): (
        'Загрузить аватар профиля',
        'Upload user profile avatar',
        'Загружает и сохраняет персональное изображение аватара для профиля текущего пользователя.',
        'Uploads and stores a custom avatar image for the current user profile.',
    ),
    ('/api/v1/auth/my-api-key', 'GET'): (
        'Получить персональный API-ключ',
        'Get personal API key',
        'Возвращает личный API-ключ текущего пользователя для интеграции со сторонними сервисами.',
        'Retrieves the personal API key of the current user for third-party integrations.',
    ),
    ('/api/v1/auth/regenerate-my-api-key', 'POST'): (
        'Перевыпустить персональный API-ключ',
        'Regenerate personal API key',
        'Генерирует новый персональный API-ключ пользователя, мгновенно аннулируя предыдущий.',
        'Generates a fresh personal API key for the current user, invalidating the previous key.',
    ),
    ('/api/v1/auth/revoke-my-api-key', 'DELETE'): (
        'Отозвать персональный API-ключ',
        'Revoke personal API key',
        'Аннулирует персональный API-ключ пользователя без автоматического перевыпуска.',
        'Revokes the personal API key of the current user, disabling key-based access.',
    ),
    ('/api/v1/auth/status', 'GET'): (
        'Проверить статус авторизации',
        'Check authentication status',
        'Возвращает данные о текущей сессии: активность, роль, статус 2FA и наличие настроенного владельца.',
        'Returns current session details: validity, role, 2FA status, and system owner presence.',
    ),
    ('/api/v1/backups', 'DELETE'): (
        'Удалить выбранные резервные копии',
        'Delete specified backups',
        'Удаляет указанные архивные файлы резервных копий с диска.',
        'Permanently deletes specified backup archive files from storage.',
    ),
    ('/api/v1/backups', 'GET'): (
        'Список резервных копий',
        'List system backups',
        'Возвращает перечень доступных архивов резервных копий базы данных и конфигурации системы.',
        'Lists available database and configuration backup archives stored on disk.',
    ),
    ('/api/v1/backups', 'POST'): (
        'Создать резервную копию системы',
        'Create manual system backup',
        'Создает полный архив резервной копии базы данных SQLite и конфигурационных файлов.',
        'Creates a comprehensive backup ZIP archive of the SQLite database and configuration files.',
    ),
    ('/api/v1/backups/inspect', 'POST'): (
        'Инспектировать загружаемый архив бэкапа',
        'Inspect uploaded backup archive',
        'Проверяет структуру и совместимость загруженного пользователем файла резервной копии перед восстановлением.',
        'Inspects and verifies structure and schema compatibility of an uploaded backup file prior to restoration.',
    ),
    ('/api/v1/backups/restore', 'POST'): (
        'Восстановить систему из загруженного файла',
        'Restore system from uploaded backup',
        'Восстанавливает базу данных и конфигурацию из переданного пользователем ZIP-файла.',
        'Restores database and configuration from a user-uploaded backup ZIP archive.',
    ),
    ('/api/v1/backups/restore-existing', 'POST'): (
        'Восстановить систему из сохраненного бэкапа',
        'Restore system from existing backup',
        'Выполняет восстановление базы данных и настроек Aliasarr из имеющегося локального архива.',
        'Restores Aliasarr database and settings from an existing local backup archive.',
    ),
    ('/api/v1/backups/stats', 'GET'): (
        'Статистика хранилища резервных копий',
        'Get backup storage statistics',
        'Возвращает общий объем, количество файлов и занятое место каталогом резервных копий.',
        'Returns total file count, storage consumption, and capacity metrics for the backup directory.',
    ),
    ('/api/v1/backups/{name}/download', 'GET'): (
        'Скачать архив резервной копии',
        'Download backup archive',
        'Отдает выбранный ZIP-архив резервной копии по его имени для локального сохранения.',
        'Downloads a specific backup ZIP archive file by its filename.',
    ),
    ('/api/v1/backups/{name}/inspect', 'GET'): (
        'Инспектировать содержимое резервной копии',
        'Inspect existing backup archive',
        'Проверяет целостность и возвращает список файлов и таблиц базы данных внутри сохраненного архива.',
        'Inspects integrity and lists files and database tables contained inside an existing backup archive.',
    ),
    ('/api/v1/blocklist', 'DELETE'): (
        'Очистить черный список релизов',
        'Clear release blocklist',
        'Удаляет все записи заблокированных релизов и хэшей из базы данных.',
        'Permanently removes all blocklisted releases and infohashes from storage.',
    ),
    ('/api/v1/blocklist', 'GET'): (
        'Список заблокированных релизов',
        'List blocklisted releases',
        'Возвращает список заблокированных релизов и торрент-хэшей с причинами блокировки и метаданными.',
        'Returns the list of blocklisted releases and torrent infohashes with rejection reasons and metadata.',
    ),
    ('/api/v1/blocklist', 'POST'): (
        'Добавить релиз в черный список',
        'Add release to blocklist',
        'Вручную добавляет раздачу или инфохэш в черный список для блокировки захвата.',
        'Manually adds a release or infohash to the blocklist to prevent downloading.',
    ),
    ('/api/v1/blocklist/clear-all', 'DELETE'): (
        'Полная очистка черного списка',
        'Purge entire blocklist',
        'Полностью очищает черный список релизов, торрентов и правил блокировки.',
        'Completely purges all entries from the blocklist database.',
    ),
    ('/api/v1/blocklist/show/{show_id_or_title}', 'DELETE'): (
        'Разблокировать тайтл',
        'Unblock show',
        'Снимает блокировку с тайтла, разрешая его поиск и скачивание.',
        'Removes a show from the blocklist, re-enabling automated search and download.',
    ),
    ('/api/v1/blocklist/shows', 'GET'): (
        'Список заблокированных тайтлов',
        'List blocked shows',
        'Возвращает список тайтлов, заблокированных для автоматического скачивания.',
        'Returns the list of shows currently excluded from automated downloads.',
    ),
    ('/api/v1/blocklist/{item_id}', 'DELETE'): (
        'Удалить запись из черного списка',
        'Remove item from blocklist',
        'Удаляет выбранную запись из черного списка, разрешая повторный захват релиза.',
        'Removes a specific entry from the blocklist, allowing the release to be captured in future searches.',
    ),
    ('/api/v1/blocklist/{item_id}', 'PUT'): (
        'Обновить запись в черном списке',
        'Update blocklist item',
        'Обновляет комментарий, причину или срок действия блокировки для записи черного списка.',
        'Updates comment, reason, or expiration details for an existing blocklist record.',
    ),
    ('/api/v1/calendar', 'GET'): (
        'Календарь релизов',
        'Get release calendar',
        'Возвращает расписание выхода серий и премьер фильмов в выбранном временном диапазоне.',
        'Returns the release schedule of upcoming and recently aired episodes and movies within a date range.',
    ),
    ('/api/v1/calendar.ics', 'GET'): (
        'Экспорт календаря в формате iCal (legacy URL)',
        'Export calendar in iCal format (legacy)',
        'Совместимый URL для экспорта расписания релизов в формате iCalendar.',
        'Legacy endpoint for exporting release schedule events in iCalendar format.',
    ),
    ('/api/v1/calendar/aliasarr.ics', 'GET'): (
        'Экспорт календаря в формате iCal (.ics)',
        'Export calendar in iCal (.ics) format',
        'Формирует файл подписки календаря в стандартном формате iCalendar для Google Calendar, Apple Calendar и Outlook.',
        'Generates an iCalendar (.ics) subscription feed compatible with Google Calendar, Apple Calendar, and Outlook.',
    ),
    ('/api/v1/calendar/search-missing', 'POST'): (
        'Поиск пропущенных серий из календаря',
        'Trigger search for missing calendar releases',
        'Запускает процедуру поиска недостающих релизов для элементов календаря с наступившей датой премьеры.',
        'Triggers an automated release search for aired calendar items missing from the local library.',
    ),
    ('/api/v1/calendar/waiting', 'GET'): (
        'Список ожидания календаря',
        'Get calendar waiting list',
        'Возвращает тайтлы и серии, ожидающие подтверждения даты премьеры или запланированные в отложенный список.',
        'Returns titles and episodes in the waiting list pending premiere date verification or deferred scheduling.',
    ),
    ('/api/v1/calendar/waiting/{show_id}/dismiss', 'POST'): (
        'Исключить тайтл из списка ожидания',
        'Dismiss title from waiting list',
        'Удаляет карточку тайтла из списка ожидания календаря.',
        'Dismisses a title from the calendar waiting list.',
    ),
    ('/api/v1/calendar/waiting/{show_id}/refresh-release-date', 'POST'): (
        'Обновить дату выхода тайтла из ожидания',
        'Refresh release date for waiting title',
        'Запрашивает актуальную дату премьеры или цифрового релиза из внешних провайдеров метаданных.',
        'Queries external metadata providers for the latest theatrical or digital release date.',
    ),
    ('/api/v1/calendar/waiting/{show_id}/restore', 'POST'): (
        'Восстановить тайтл в список ожидания',
        'Restore title to waiting list',
        'Возвращает ранее отклоненный тайтл обратно в список ожидания календаря.',
        'Restores a previously dismissed title back to the active calendar waiting list.',
    ),
    ('/api/v1/calendar/{show_id}/move-to-calendar', 'POST'): (
        'Перенести тайтл из ожидания в активный календарь',
        'Move title from waiting to active calendar',
        'Переводит тайтл из очереди ожидания в постоянную сетку календаря релизов.',
        'Transfers a show from the waiting list to the scheduled release calendar.',
    ),
    ('/api/v1/calendar/{show_id}/move-to-waiting', 'POST'): (
        'Перенести тайтл из календаря в список ожидания',
        'Move title from calendar to waiting list',
        'Перемещает тайтл из сетки календаря в отложенный список ожидания релизов.',
        'Transfers a show from the calendar into the deferred waiting list.',
    ),
    ('/api/v1/calendar/{show_id}/schedule-weekly', 'POST'): (
        'Запланировать еженедельный выход серий',
        'Schedule weekly recurring release',
        'Автоматически формирует еженедельное расписание выхода серий тайтла в календаре.',
        'Automatically schedules recurring weekly release dates for upcoming episodes of the show.',
    ),
    ('/api/v1/collections', 'GET'): (
        'Список коллекций и саг фильмов TMDb',
        'List TMDb movie collections',
        'Возвращает каталог саг и коллекций фильмов TMDb с прогрессом наличия частей в медиатеке.',
        'Returns TMDb movie collections and sagas along with collection completeness status in the library.',
    ),
    ('/api/v1/collections', 'POST'): (
        'Добавить коллекцию фильмов',
        'Add movie collection',
        'Добавляет новую сагу фильмов в базу Aliasarr по идентификатору коллекции TMDb.',
        'Adds a new movie saga into the Aliasarr catalog using its TMDb Collection ID.',
    ),
    ('/api/v1/collections/refresh-all', 'POST'): (
        'Синхронизировать все коллекции с TMDb',
        'Sync all collections with TMDb',
        'Запускает фоновую синхронизацию метаданных, постеров и состава фильмов для всех коллекций через TMDb API.',
        'Triggers a background synchronization of metadata, posters, and installments for all collections via TMDb API.',
    ),
    ('/api/v1/collections/{collection_id}', 'DELETE'): (
        'Удалить коллекцию из системы',
        'Delete movie collection',
        'Удаляет запись о коллекции из каталога Aliasarr (файлы фильмов на диске сохраняются).',
        'Deletes a collection record from the Aliasarr catalog (movie files on disk remain untouched).',
    ),
    ('/api/v1/collections/{collection_id}', 'GET'): (
        'Детальная информация о коллекции фильмов',
        'Get movie collection details',
        'Возвращает подробную карточку коллекции TMDb, список частей франшизы и статус наличия каждого фильма.',
        'Returns comprehensive movie collection details, installment list, and library presence status for each title.',
    ),
    ('/api/v1/collections/{collection_id}', 'PUT'): (
        'Обновить параметры коллекции',
        'Update movie collection settings',
        'Обновляет настройки мониторинга, профиль качества и параметры карточки коллекции.',
        'Updates monitoring preferences, quality profile, and metadata flags for a movie collection.',
    ),
    ('/api/v1/collections/{collection_id}/backdrop', 'GET'): (
        'Получить фоновое изображение коллекции',
        'Get collection backdrop',
        'Отдает широкоформатное фоновое изображение (backdrop) коллекции фильмов.',
        'Serves the cached local backdrop artwork for the movie collection.',
    ),
    ('/api/v1/collections/{collection_id}/import-missing', 'POST'): (
        'Добавить недостающие фильмы саги',
        'Add missing collection movies',
        'Автоматически создает карточки в медиатеке для недостающих частей саги.',
        'Automatically creates library entries for missing movies in the collection.',
    ),
    ('/api/v1/collections/{collection_id}/poster', 'GET'): (
        'Получить постер коллекции',
        'Get collection poster',
        'Отдает изображение постера коллекции фильмов из локального кэша обложек.',
        'Serves the cached local poster image file for the movie collection.',
    ),
    ('/api/v1/collections/{collection_id}/refresh', 'POST'): (
        'Обновить метаданные коллекции с TMDb',
        'Refresh single collection from TMDb',
        'Обновляет состав, описание, постеры и даты премьер для указанной коллекции из базы TMDb.',
        'Refreshes installments, description, posters, and release dates for the specified TMDb collection.',
    ),
    ('/api/v1/custom-formats', 'GET'): (
        'Список кастомных форматов ранжирования',
        'List custom scoring formats',
        'Возвращает все настроенные кастомные форматы для ранжирования качества, релиз-групп и параметров видео.',
        'Returns all configured Custom Formats for scoring release quality, release groups, and audio/video specs.',
    ),
    ('/api/v1/custom-formats', 'POST'): (
        'Создать новый кастомный формат',
        'Create new custom format',
        'Создает новый кастомный формат ранжирования с условиями совпадения тегов, регулярок и весовыми баллами.',
        'Creates a new release scoring custom format with conditions, regular expressions, and score values.',
    ),
    ('/api/v1/custom-formats/{format_id}', 'DELETE'): (
        'Удалить кастомный формат',
        'Delete custom format',
        'Удаляет кастомный формат ранжирования релизов из системы.',
        'Deletes a release scoring custom format by its identifier.',
    ),
    ('/api/v1/custom-formats/{format_id}', 'GET'): (
        'Параметры кастомного формата',
        'Get custom format details',
        'Возвращает детальную конфигурацию формата, включая вложенные спецификации и баллы.',
        'Retrieves the detailed configuration of a custom format, including conditions and score modifiers.',
    ),
    ('/api/v1/custom-formats/{format_id}', 'PUT'): (
        'Обновить кастомный формат',
        'Update custom format',
        'Обновляет условия, регулярные выражения, название и весовые баллы кастомного формата.',
        'Updates condition specifications, regex patterns, title, and score weighting for an existing format.',
    ),
    ('/api/v1/custom-formats/{format_id}/reset', 'POST'): (
        'Сбросить кастомный формат к стандарту',
        'Reset custom format to default',
        'Сбрасывает конфигурацию предустановленного кастомного формата к эталонному заводскому состоянию.',
        'Resets a pre-installed custom format back to its original default configuration.',
    ),
    ('/api/v1/dataset', 'DELETE'): (
        'Очистить сохраненный датасет',
        'Clear benchmark dataset',
        'Удаляет все собранные тестовые примеры из базы обучающего датасета.',
        'Clears all collected benchmark release titles from the dataset storage.',
    ),
    ('/api/v1/dataset/data', 'GET'): (
        'Получить данные обучающего датасета',
        'Get benchmark dataset data',
        'Возвращает список размеченных примеров названий раздач для проверки точности парсера.',
        'Returns benchmark training release titles for parser accuracy validation.',
    ),
    ('/api/v1/dataset/diagnose', 'POST'): (
        'Запустить диагностику парсера на датасете',
        'Run parser diagnostics on dataset',
        'Тестирует парсер названий на обучающем датасете и формирует отчет об ошибках распознавания.',
        'Executes parser diagnostics across the benchmark dataset and reports misclassifications.',
    ),
    ('/api/v1/dataset/export', 'GET'): (
        'Экспортировать датасет в JSON',
        'Export dataset as JSON',
        'Выгружает весь собранный обучающий набор данных в виде JSON-файла.',
        'Exports the entire benchmark parser dataset as a downloadable JSON file.',
    ),
    ('/api/v1/dataset/harvest', 'POST'): (
        'Запустить сбор обучающего датасета',
        'Start dataset harvesting',
        'Запускает фоновый процесс сбора и нормализации названий релизов с подключенных трекеров.',
        'Launches background collection and normalization of release titles from active indexers.',
    ),
    ('/api/v1/dataset/status', 'GET'): (
        'Статус сбора обучающего датасета',
        'Get dataset harvest status',
        'Возвращает текущий прогресс, количество обработанных раздач и статус процесса сбора.',
        'Returns current progress, harvested item counts, and status of the collection job.',
    ),
    ('/api/v1/dataset/stop', 'POST'): (
        'Остановить сбор обучающего датасета',
        'Stop dataset harvesting',
        'Прерывает выполняющийся фоновый процесс сбора названий релизов.',
        'Stops the ongoing background release title harvesting task.',
    ),
    ('/api/v1/download-clients', 'GET'): (
        'Список подключенных торрент-клиентов',
        'List connected download clients',
        'Возвращает перечень настроенных торрент-клиентов (qBittorrent, Transmission, Deluge, rTorrent).',
        'Lists configured download clients (qBittorrent, Transmission, Deluge, rTorrent) and their status.',
    ),
    ('/api/v1/download-clients', 'POST'): (
        'Подключить новый торрент-клиент',
        'Connect new download client',
        'Добавляет конфигурацию нового торрент-клиента с параметрами хоста, порта, учетных данных и лимитов раздачи.',
        'Registers a new download client with host, port, credentials, category mapping, and seeding limits.',
    ),
    ('/api/v1/download-clients/test', 'POST'): (
        'Проверить временные настройки клиента',
        'Test temporary download client settings',
        'Проверяет соединение с торрент-клиентом по переданным временным параметрам без сохранения в базу.',
        'Tests download client connection parameters dynamically without saving them to the database.',
    ),
    ('/api/v1/download-clients/{dc_id}', 'DELETE'): (
        'Отключить торрент-клиент',
        'Remove download client',
        'Удаляет торрент-клиент из конфигурации Aliasarr.',
        'Removes a download client from the Aliasarr configuration.',
    ),
    ('/api/v1/download-clients/{dc_id}', 'PUT'): (
        'Обновить параметры торрент-клиента',
        'Update download client settings',
        'Обновляет настройки подключения, учетные данные, приоритеты и лимиты сидирования для клиента.',
        'Updates connection settings, credentials, priority rankings, and seeding ratio/time limits for a client.',
    ),
    ('/api/v1/download-clients/{dc_id}/check', 'POST'): (
        'Проверить статус доступности торрент-клиента',
        'Check download client availability',
        'Выполняет диагностический запрос к торрент-клиенту и обновляет статус подключения и ошибок.',
        'Executes a diagnostic query against the download client and updates connection and error status.',
    ),
    ('/api/v1/download-clients/{dc_id}/test', 'POST'): (
        'Проверить соединение с сохраненным клиентом',
        'Test saved download client connection',
        'Проверяет сетевую доступность и корректность авторизации для сохраненного торрент-клиента.',
        'Tests network reachability and authentication credentials for a saved download client.',
    ),
    ('/api/v1/episodes/{episode_id}/air-date', 'PUT'): (
        'Установить дату выхода серии',
        'Set custom episode air date',
        'Вручную задает дату и время премьеры конкретного эпизода в календаре.',
        'Manually overrides the air date and time for a specific episode in the calendar.',
    ),
    ('/api/v1/episodes/{episode_id}/monitor', 'PUT'): (
        'Изменить статус мониторинга серии',
        'Set episode monitoring status',
        'Переключает статус мониторинга конкретного эпизода (WANTED или IGNORED).',
        'Toggles the monitoring status for a specific episode between WANTED and IGNORED.',
    ),
    ('/api/v1/episodes/{episode_id}/search', 'POST'): (
        'Найти и захватить релиз для серии',
        'Search and grab episode',
        'Выполняет целенаправленный поиск релизов для одного эпизода и отправляет лучший вариант в загрузчик.',
        'Executes a targeted indexer search for a single episode and sends the optimal release to the client.',
    ),
    ('/api/v1/episodes/{episode_id}/upgrade', 'POST'): (
        'Переключить режим апгрейда качества серии',
        'Toggle episode quality upgrade',
        'Включает или выключает автоматический поиск более качественной версии для существующей серии.',
        'Enables or disables automated quality upgrade searches for an already acquired episode.',
    ),
    ('/api/v1/events', 'GET'): (
        'Журнал системных событий',
        'List system events',
        'Возвращает список зафиксированных системой событий (информационные, предупреждения, ошибки).',
        'Returns recorded system events categorized by severity: info, warning, and error.',
    ),
    ('/api/v1/filesystem/browse', 'GET'): (
        'Просмотр файловой системы хоста',
        'Browse host filesystem directories',
        'Возвращает список папок и файлов на хосте для выбора корневых путей в интерфейсе.',
        'Browses host filesystem directories to facilitate path selection in configuration forms.',
    ),
    ('/api/v1/filesystem/mkdir', 'POST'): (
        'Создать новую папку на хосте',
        'Create new directory on host',
        'Создает новую директорию в файловой системе с правильными правами доступа 0777.',
        'Creates a new directory on the host filesystem with standard open permissions (0777).',
    ),
    ('/api/v1/health', 'GET'): (
        'Проверка доступности и работоспособности сервиса',
        'Service health check',
        'Возвращает статус доступности сервиса Aliasarr и время непрерывной работы.',
        'Returns service health, operational readiness status, and uptime.',
    ),
    ('/api/v1/health-check', 'GET'): (
        'Комплексная диагностика системы',
        'System health and dependency check',
        'Выполняет проверку состояния базы данных, дискового пространства, планировщика и фоновых процессов.',
        'Performs diagnostic checks across database integrity, disk space, scheduler, and background services.',
    ),
    ('/api/v1/history', 'GET'): (
        'История захватов и импорта релизов',
        'Get release history',
        'Возвращает журнал выполненных захватов раздач, скачиваний и завершенных импортов файлов на диск.',
        'Returns the chronological event log of grabbed releases, downloads, and completed file imports.',
    ),
    ('/api/v1/indexers', 'GET'): (
        'Список настроенных торрент-индексаторов',
        'List configured torrent indexers',
        'Возвращает перечень подключенных торрент-трекеров (Torznab/Newznab) и их текущие статусы доступности.',
        'Lists configured torrent indexers (Torznab/Newznab) and their health and rate-limiting status.',
    ),
    ('/api/v1/indexers', 'POST'): (
        'Добавить новый торрент-индексатор',
        'Add new torrent indexer',
        'Добавляет новый торрент-индексатор с URL, API-ключом, категориями поиска и персональными лимитами запросов.',
        'Adds a new torrent indexer with Torznab URL, API key, search categories, and custom rate-limiting settings.',
    ),
    ('/api/v1/indexers/grab', 'POST'): (
        'Отправить релиз в торрент-клиент',
        'Grab release to download client',
        'Загружает выбранный .torrent файл или magnet-ссылку и отправляет задачу в целевой торрент-клиент.',
        'Downloads the selected .torrent file or magnet URI and queues it in the chosen download client.',
    ),
    ('/api/v1/indexers/search-custom', 'GET'): (
        'Произвольный поиск по индексаторам',
        'Custom search on indexers',
        'Выполняет поиск торрент-раздач по произвольной поисковой строке и категориям.',
        'Searches configured torrent indexers using custom query strings and categories.',
    ),
    ('/api/v1/indexers/search/{show_id}', 'GET'): (
        'Поиск релизов для тайтла на индексаторах',
        'Search indexers for show releases',
        'Выполняет интерактивный поиск раздач для указанного тайтла по всем активным индексаторам.',
        'Queries all active indexers for releases matching the specified show title and aliases.',
    ),
    ('/api/v1/indexers/test', 'POST'): (
        'Проверить параметры индексатора',
        'Test indexer configuration',
        'Проверяет связь с Torznab/Newznab сервером по временным параметрам без сохранения в базу.',
        'Tests indexer connection and capabilities without committing changes to the database.',
    ),
    ('/api/v1/indexers/{indexer_id}', 'DELETE'): (
        'Удалить торрент-индексатор',
        'Delete torrent indexer',
        'Удаляет торрент-индексатор из конфигурации системы.',
        'Removes a torrent indexer from the system configuration.',
    ),
    ('/api/v1/indexers/{indexer_id}', 'PUT'): (
        'Обновить параметры торрент-индексатора',
        'Update torrent indexer settings',
        'Обновляет адрес, API-ключ, категории или настройки лимитера запросов для существующего индексатора.',
        'Updates URL, API key, categories, or rate-limiting parameters for an existing indexer.',
    ),
    ('/api/v1/indexers/{indexer_id}/check', 'POST'): (
        'Проверить доступность сохраненного индексатора',
        'Check saved indexer availability',
        'Выполняет тестовый запрос возможностей к сохраненному трекеру и обновляет статус работоспособности.',
        'Executes a health check query against a saved indexer and refreshes its operational status.',
    ),
    ('/api/v1/indexers/{indexer_id}/test', 'POST'): (
        'Проверить связь с торрент-индексатором',
        'Test indexer connection',
        'Выполняет проверочный запрос возможностей (caps) к сохраненному торрент-индексатору.',
        'Executes a capabilities test query against a saved torrent indexer.',
    ),
    ('/api/v1/journal', 'DELETE'): (
        'Очистить журнал логов',
        'Clear application log journal',
        'Очищает сохраненные записи системного журнала работы приложения.',
        'Clears stored log entries from the application journal.',
    ),
    ('/api/v1/journal', 'GET'): (
        'Просмотр системного лога (журнала)',
        'List application log entries',
        'Возвращает строки системного журнала работы Aliasarr с фильтрацией по уровню логирования.',
        'Retrieves log entries from the Aliasarr runtime journal with level filtering.',
    ),
    ('/api/v1/journal/download', 'GET'): (
        'Скачать системный лог в текстовом виде',
        'Download log journal as plain text',
        'Формирует текстовый файл полного журнала логов Aliasarr для диагностики и техподдержки.',
        'Generates and downloads the full Aliasarr application log as a plain text file for troubleshooting.',
    ),
    ('/api/v1/journal/purge-old', 'POST'): (
        'Удалить устаревшие записи логов',
        'Purge expired log entries',
        'Удаляет записи логов старше установленного периода хранения для экономии дискового пространства.',
        'Purges log entries older than the configured retention threshold to conserve storage.',
    ),
    ('/api/v1/metadata-sources', 'GET'): (
        'Список источников метаданных',
        'List metadata sources',
        'Возвращает настроенные провайдеры метаданных (Kinopoisk, TMDb, TheTVDb, AniList, Shikimori, TVMaze) и их приоритеты.',
        'Returns configured external metadata providers (Kinopoisk, TMDb, TheTVDb, AniList, Shikimori, TVMaze) and priority rankings.',
    ),
    ('/api/v1/metadata-sources', 'POST'): (
        'Добавить источник метаданных',
        'Add metadata source',
        'Регистрирует новый внешний источник метаданных с параметрами доступа и приоритетом выбора.',
        'Registers a new metadata source with API credentials and provider priority level.',
    ),
    ('/api/v1/metadata-sources/cleanup-aliases', 'POST'): (
        'Очистить недопустимые алиасы',
        'Clean up unallowed aliases',
        'Удаляет дублирующиеся или некорректные поисковые алиасы, очищая базу данных.',
        'Cleans up malformed, redundant, or disallowed title search aliases across the database.',
    ),
    ('/api/v1/metadata-sources/image-proxy', 'GET'): (
        'Проксирование изображений обложек',
        'Proxy external cover images',
        'Безопасно проксирует внешние изображения постеров и баннеров, предотвращая блокировки CORS.',
        'Proxies external cover and artwork images to prevent CORS and mixed-content restrictions.',
    ),
    ('/api/v1/metadata-sources/import', 'POST'): (
        'Импортировать тайтл из источника метаданных',
        'Import title from metadata source',
        'Создает карточку фильма или сериала в медиатеке на основе результатов поиска метаданных.',
        'Creates a new show or movie library record based on metadata search results.',
    ),
    ('/api/v1/metadata-sources/search', 'GET'): (
        'Поиск по всем источникам метаданных',
        'Search across all metadata sources',
        'Выполняет параллельный поиск фильмов и сериалов по всем активным внешним базам метаданных.',
        'Executes aggregated multi-provider search for movies and series across all active metadata APIs.',
    ),
    ('/api/v1/metadata-sources/test', 'POST'): (
        'Проверить подключение к источнику метаданных',
        'Test metadata source connection',
        'Проверяет валидность API-ключа и доступность сервиса по переданным временным параметрам.',
        'Tests API key validity and remote service connectivity using temporary configuration parameters.',
    ),
    ('/api/v1/metadata-sources/{source_id}', 'DELETE'): (
        'Удалить источник метаданных',
        'Delete metadata source',
        'Удаляет источник метаданных из конфигурации системы.',
        'Deletes a metadata source from the system configuration.',
    ),
    ('/api/v1/metadata-sources/{source_id}', 'PUT'): (
        'Обновить источник метаданных',
        'Update metadata source',
        'Обновляет API-ключ, активность и весовой приоритет для источника метаданных.',
        'Updates API credentials, active status, and priority weight for a metadata source.',
    ),
    ('/api/v1/metadata-sources/{source_id}/search', 'GET'): (
        'Поиск в конкретном источнике метаданных',
        'Search specific metadata source',
        'Ищет тайтлы только в указанном провайдере метаданных (например, только на Кинопоиске).',
        'Searches titles strictly within a specified metadata provider (e.g. Kinopoisk or TMDb).',
    ),
    ('/api/v1/notifications', 'GET'): (
        'Список каналов уведомлений',
        'List notification channels',
        'Возвращает перечень настроенных каналов доставки уведомлений (Telegram, Discord, Webhook и др.).',
        'Returns configured notification endpoints (Telegram, Discord, Webhook, Pushover, etc.).',
    ),
    ('/api/v1/notifications', 'POST'): (
        'Сохранить конфигурацию уведомлений',
        'Create notification channel',
        'Создает новую конфигурацию канала отправки системных и загрузочных уведомлений.',
        'Creates settings for a new notification channel handling system and download events.',
    ),
    ('/api/v1/notifications/test', 'POST'): (
        'Проверить несохраненные параметры уведомления',
        'Test unsaved notification settings',
        'Отправляет тестовое уведомление по переданным временным параметрам без сохранения в базу.',
        'Sends a test notification using temporary parameters without committing to the database.',
    ),
    ('/api/v1/notifications/{config_id}', 'DELETE'): (
        'Удалить канал уведомлений',
        'Delete notification channel',
        'Удаляет выбранную конфигурацию канала уведомлений из системы.',
        'Removes a notification channel configuration from the system.',
    ),
    ('/api/v1/notifications/{config_id}', 'PUT'): (
        'Обновить параметры канала уведомлений',
        'Update notification channel',
        'Обновляет токен, URL вебхука, типы триггеров и статус активности канала уведомлений.',
        'Updates token, webhook URL, trigger event types, and active status of a notification channel.',
    ),
    ('/api/v1/notifications/{config_id}/test', 'POST'): (
        'Проверить сохраненный канал уведомлений',
        'Test saved notification channel',
        'Отправляет тестовое диагностическое сообщение в сохраненный канал уведомлений.',
        'Sends a test alert message to a configured notification channel to verify delivery.',
    ),
    ('/api/v1/organizer/preview', 'POST'): (
        'Предпросмотр имени файла при организации',
        'Preview organized destination filename',
        'Генерирует итоговое целевое имя файла и путь к папке по шаблонам переименования медиатеки.',
        'Generates expected destination filename and folder path based on configured library naming patterns.',
    ),
    ('/api/v1/quality-profiles', 'GET'): (
        'Список профилей качества',
        'List quality profiles',
        'Возвращает все настроенные профили качества с целевыми разрешениями, кодеками и лимитами размеров.',
        'Returns all configured quality profiles with resolution targets, allowed codecs, and size boundaries.',
    ),
    ('/api/v1/quality-profiles/voiceovers', 'GET'): (
        'Каталог пресетов озвучек',
        'List voiceover presets',
        'Возвращает структурированный каталог из 44 заготовленных пресетов озвучек и регулярных выражений для профилей качества.',
        'Returns structured catalog of 44 predefined voiceover studio presets and regex patterns for quality profiles.',
    ),
    ('/api/v1/quality-profiles', 'POST'): (
        'Создать новый профиль качества',
        'Create quality profile',
        'Создает новый профиль ранжирования и фильтрации качества релизов.',
        'Registers a new quality profile specifying release ranking rules and target formats.',
    ),
    ('/api/v1/quality-profiles/{profile_id}', 'DELETE'): (
        'Удалить профиль качества',
        'Delete quality profile',
        'Удаляет профиль качества из системы (если он не назначен активным тайтлам).',
        'Deletes a quality profile by its identifier (if not assigned to active library titles).',
    ),
    ('/api/v1/quality-profiles/{profile_id}', 'PUT'): (
        'Обновить параметры профиля качества',
        'Update quality profile',
        'Обновляет список разрешенных качеств, порядок предпочтений и целевые форматы профиля.',
        'Updates allowed quality tiers, preference rankings, and target formats for a profile.',
    ),
    ('/api/v1/queue', 'GET'): (
        'Состояние очереди загрузок',
        'Get download queue status',
        'Возвращает текущие активные загрузки из всех подключенных торрент-клиентов со скоростями и прогрессом.',
        'Returns active download tasks from all connected torrent clients with speeds, ETA, and progress.',
    ),
    ('/api/v1/queue/check', 'POST'): (
        'Проверить статус очереди загрузок',
        'Trigger download queue check',
        'Принудительно опрашивает торрент-клиенты и инициирует импорт завершенных загрузок в библиотеку.',
        'Polls download clients immediately and triggers automated import of completed downloads into the library.',
    ),
    ('/api/v1/queue/{torrent_hash}', 'DELETE'): (
        'Удалить задачу из очереди загрузки',
        'Delete queue item',
        'Удаляет раздачу из очереди торрент-клиента с возможностью удаления незавершенных файлов на диске.',
        'Removes a torrent job from the download client queue with optional deletion of incomplete disk files.',
    ),
    ('/api/v1/queue/{torrent_hash}/pause', 'POST'): (
        'Приостановить загрузку раздачи',
        'Pause torrent download',
        'Ставит на паузу загрузку торрент-раздачи в соответствующем торрент-клиенте.',
        'Pauses downloading of the specified torrent inside its respective download client.',
    ),
    ('/api/v1/queue/{torrent_hash}/resume', 'POST'): (
        'Возобновить загрузку раздачи',
        'Resume torrent download',
        'Возобновляет приостановленную загрузку раздачи в торрент-клиенте.',
        'Resumes a paused torrent download inside its respective download client.',
    ),
    ('/api/v1/release-logs', 'DELETE'): (
        'Очистить историю решений по релизам',
        'Clear release decision logs',
        'Полностью очищает сохраненные журналы решений и парсинга релизов.',
        'Permanently clears all stored release evaluation and parsing decision logs.',
    ),
    ('/api/v1/release-logs', 'GET'): (
        'История решений парсера по релизам',
        'Get release grab and decision logs',
        'Возвращает детальный журнал решений Decision Engine: оценки качества, причины отклонения и скоринг.',
        'Returns granular trace logs from the Decision Engine: release scores, rejection reasons, and parsing details.',
    ),
    ('/api/v1/release-logs/export', 'GET'): (
        'Экспорт журнала решений по релизам',
        'Export release decision logs',
        'Выгружает историю решений парсера и захвата релизов в виде структурированного файла.',
        'Exports release evaluation logs and Decision Engine results as a structured export file.',
    ),
    ('/api/v1/search/wanted', 'POST'): (
        'Запустить поиск разыскиваемых серий (синоним)',
        'Trigger wanted search (alias)',
        'Альтернативный эндпоинт запуска цикла поиска для разыскиваемых серий и фильмов.',
        'Alternative endpoint for triggering an auto-search cycle for wanted episodes and movies.',
    ),
    ('/api/v1/settings', 'GET'): (
        'Получить текущие конфигурационные настройки',
        'Get system configuration settings',
        'Возвращает полные настройки системы: корневые директории, порты, параметры парсера и профили качества.',
        'Retrieves system configuration settings: root directories, service ports, parser flags, and quality profiles.',
    ),
    ('/api/v1/settings', 'PUT'): (
        'Сохранить конфигурационные настройки системы',
        'Save system configuration settings',
        'Обновляет глобальные параметры Aliasarr: папки библиотеки, язык интерфейса, лимиты и правила парсера.',
        'Updates global Aliasarr settings: media paths, interface language, limits, and naming parser rules.',
    ),
    ('/api/v1/settings/regenerate-api-key', 'POST'): (
        'Перевыпустить системный API-ключ',
        'Regenerate main system API key',
        'Создает новый системный API-ключ и делает недействительным предыдущий ключ.',
        'Generates a new system-wide master API key and immediately invalidates the previous key.',
    ),
    ('/api/v1/settings/ssl', 'GET'): (
        'Получить настройки SSL-сертификата',
        'Get SSL certificate settings',
        'Возвращает статус активности HTTPS, срок действия сертификата и доменные имена.',
        'Returns HTTPS encryption status, SSL certificate expiration date, and domain validity.',
    ),
    ('/api/v1/settings/ssl', 'POST'): (
        'Обновить параметры SSL-сертификата',
        'Update SSL certificate settings',
        'Сохраняет настройки HTTPS, пользовательские сертификаты и приватные ключи.',
        'Saves HTTPS configuration, custom certificate files, and TLS private key parameters.',
    ),
    ('/api/v1/settings/ssl/regenerate', 'POST'): (
        'Перевыпустить самоподписанный SSL-сертификат',
        'Regenerate self-signed SSL certificate',
        'Создает новый самоподписанный сертификат SSL и закрытый ключ для защищенного доступа по HTTPS.',
        'Generates a fresh self-signed SSL certificate and private key for secure HTTPS access.',
    ),
    ('/api/v1/shows', 'GET'): (
        'Получить список всех тайтлов медиатеки',
        'List all library shows',
        'Возвращает карточки всех фильмов, сериалов и аниме с прогрессом сезонов, статусом файлов и постерами.',
        'Returns all movies, series, and anime in the library with episode progress, file counts, and cover art.',
    ),
    ('/api/v1/shows', 'POST'): (
        'Добавить новый тайтл в медиатеку',
        'Add new show to library',
        'Добавляет новый фильм или сериал в медиатеку с привязкой к источнику метаданных и корневой папке.',
        'Adds a new movie or show to the media library linked to an external metadata ID and destination path.',
    ),
    ('/api/v1/shows/manual-import/execute-all', 'POST'): (
        'Выполнить глобальный ручной импорт файлов',
        'Execute global manual import',
        'Выполняет массовый импорт выбранных файлов в соответствующие папки тайтлов медиатеки.',
        'Executes batch import of selected media files into their respective library destinations.',
    ),
    ('/api/v1/shows/manual-import/scan-all', 'POST'): (
        'Глобальное сканирование для ручного импорта',
        'Scan files for global manual import',
        'Сканирует загрузочную директорию на наличие видеофайлов для ручного импорта во все тайтлы медиатеки.',
        'Scans download folders for media files eligible for manual import across all library titles.',
    ),
    ('/api/v1/shows/{show_id}', 'DELETE'): (
        'Удалить тайтл из медиатеки',
        'Delete show from library',
        'Удаляет карточку тайтла из базы данных Aliasarr с возможностью сохранения или удаления файлов на диске.',
        'Deletes a title from the Aliasarr database, with an option to preserve or purge disk files.',
    ),
    ('/api/v1/shows/{show_id}', 'GET'): (
        'Получить подробные данные тайтла по ID',
        'Get show details by ID',
        'Возвращает полную карточку тайтла, включая алиасы, сезоны, эпизоды, профиль качества и путь на диске.',
        'Retrieves complete show details including aliases, seasons, episodes, quality profile, and storage path.',
    ),
    ('/api/v1/shows/{show_id}', 'PUT'): (
        'Обновить метаданные и настройки тайтла',
        'Update show metadata and settings',
        'Обновляет параметры карточки тайтла: профиль качества, корневую папку, мониторинг и настройки тегов.',
        'Updates title configuration: quality profile, root folder, monitoring flags, and tag associations.',
    ),
    ('/api/v1/shows/{show_id}/aliases', 'POST'): (
        'Добавить поисковый алиас к тайтлу',
        'Add search alias to show',
        'Добавляет альтернативное мультиязычное название (алиас) для поиска релизов на трекерах.',
        'Adds an alternative multi-language title alias for querying indexers with localized names.',
    ),
    ('/api/v1/shows/{show_id}/aliases/{alias_id}', 'DELETE'): (
        'Удалить поисковый алиас',
        'Delete search alias',
        'Удаляет альтернативное поисковое название из карточки тайтла.',
        'Removes a search alias from the title configuration.',
    ),
    ('/api/v1/shows/{show_id}/aliases/{alias_id}', 'PUT'): (
        'Обновить поисковый алиас',
        'Update search alias',
        'Изменяет текст алиаса, привязку к сезону, смещение номеров серий (+Offset) или признак чистого поиска.',
        'Modifies alias text, season binding, episode number offset (+Offset), or clean search flags.',
    ),
    ('/api/v1/shows/{show_id}/all_seasons/monitor', 'PUT'): (
        'Переключить мониторинг всех сезонов',
        'Toggle monitoring for all seasons',
        'Массово включает или выключает отслеживание всех существующих сезонов тайтла.',
        'Batch updates the monitoring status across all seasons of the show.',
    ),
    ('/api/v1/shows/{show_id}/auto-search', 'POST'): (
        'Запустить принудительный автопоиск тайтла',
        'Force auto-search for show',
        'Принудительно запускает поиск и автоматический захват лучших релизов для тайтла.',
        'Forces immediate auto-search and grabbing of optimal releases for the show.',
    ),
    ('/api/v1/shows/{show_id}/change-folder', 'POST'): (
        'Сменить папку тайтла',
        'Change title folder',
        'Меняет папку тайтла: переносит содержимое старой папки в новую и перепривязывает пути серий, либо только обновляет путь в базе, если файлы уже перемещены вручную.',
        'Changes the folder of a title: either moves the contents of the old folder to the new one and re-points episode paths, or only updates the stored path when the files were already moved by hand.',
    ),
    ('/api/v1/shows/{show_id}/change-folder/preview', 'GET'): (
        'Предпросмотр смены папки тайтла',
        'Preview title folder change',
        'Сообщает, что произойдёт при смене папки: объём и количество переносимых файлов, существует ли целевая папка и не занята ли она другим тайтлом.',
        'Reports what a folder change would do: the size and number of files to move, whether the target folder exists and whether another title already uses it.',
    ),
    ('/api/v1/shows/{show_id}/delete-content', 'POST'): (
        'Удалить файлы тайтла с диска',
        'Delete show files from disk',
        'Физически удаляет файлы медиаконтента и директорию тайтла с диска, сохраняя или сбрасывая карточку.',
        'Physically deletes media files and folder from disk while resetting library status.',
    ),
    ('/api/v1/shows/{show_id}/episodes', 'GET'): (
        'Получить список эпизодов тайтла',
        'List show episodes',
        'Возвращает все эпизоды тайтла с информацией о наличии на диске, размере, статусе мониторинга и дате выхода.',
        'Lists all episodes of a show with file presence details, file size, monitoring status, and air dates.',
    ),
    ('/api/v1/shows/{show_id}/fix-permissions', 'POST'): (
        'Исправить права доступа к папке тайтла',
        'Fix permissions for show folder',
        'Принудительно рекурсивно выставляет стандартные права чтения/записи (0777/0666) для файлов тайтла.',
        'Recursively applies standard read/write permissions (0777/0666) to all files in the show directory.',
    ),
    ('/api/v1/shows/{show_id}/manual-import/execute', 'POST'): (
        'Выполнить ручной импорт файлов в тайтл',
        'Execute manual import for show',
        'Перемещает или копирует выбранные видеофайлы в медиатеку с правильным переименованием и связыванием.',
        'Moves or copies selected video files into library storage with organized naming and episode linking.',
    ),
    ('/api/v1/shows/{show_id}/manual-import/scan', 'POST'): (
        'Сканировать файлы для ручного импорта в тайтл',
        'Scan files for manual import to show',
        'Сканирует указанную папку на наличие видеофайлов для сопоставления с сериями данного тайтла.',
        'Scans a specified folder for video files and proposes mapping them to episodes of the show.',
    ),
    ('/api/v1/shows/{show_id}/monitor', 'PUT'): (
        'Переключить мониторинг тайтла',
        'Toggle show monitoring',
        'Включает или выключает общий флаг мониторинга для всего тайтла.',
        'Toggles the global monitoring flag across the entire show.',
    ),
    ('/api/v1/shows/{show_id}/poster', 'GET'): (
        'Получить постер тайтла',
        'Get show poster image',
        'Отдает графический файл постера тайтла из локального кэша обложек.',
        'Serves the cached local poster image file for the show.',
    ),
    ('/api/v1/shows/{show_id}/refresh-cover', 'POST'): (
        'Обновить постер тайтла из сети',
        'Refresh show cover art',
        'Загружает актуальный постер высокого разрешения из подключенного источника метаданных.',
        'Downloads fresh high-resolution poster artwork from the active metadata provider.',
    ),
    ('/api/v1/shows/{show_id}/remap', 'POST'): (
        'Сменить привязку тайтла к метаданным',
        'Remap show metadata ID',
        'Перепривязывает тайтл к другому идентификатору Kinopoisk, TMDb или TheTVDb с полной перезагрузкой данных.',
        'Remaps the show to a different Kinopoisk, TMDb, or TheTVDb ID and reloads episode and artwork data.',
    ),
    ('/api/v1/shows/{show_id}/rename/execute', 'POST'): (
        'Выполнить переименование файлов тайтла',
        'Execute file renaming for show',
        'Переименовывает и организует видеофайлы тайтла на диске согласно утвержденному предпросмотру.',
        'Renames and reorganizes on-disk media files for the show according to naming patterns.',
    ),
    ('/api/v1/shows/{show_id}/rename/preview', 'GET'): (
        'Предпросмотр переименования файлов тайтла',
        'Preview file renaming for show',
        'Генерирует diff текущих и новых имен файлов тайтла в соответствии с шаблоном переименования.',
        'Generates a preview diff showing current vs organized filenames based on the naming template.',
    ),
    ('/api/v1/shows/{show_id}/search', 'POST'): (
        'Запустить автопоиск релизов для тайтла',
        'Search releases for show',
        'Запускает поиск релизов на всех индексаторах для разыскиваемых серий выбранного тайтла.',
        'Initiates an automated release search across all indexers for wanted episodes of the show.',
    ),
    ('/api/v1/shows/{show_id}/search-episode', 'POST'): (
        'Поиск релизов для выбранной серии',
        'Search releases for episode',
        'Выполняет поиск релизов на индексаторах для одной конкретной серии тайтла.',
        'Searches configured indexers for releases matching a single selected episode.',
    ),
    ('/api/v1/shows/{show_id}/search-episodes', 'POST'): (
        'Пакетный поиск релизов для набора серий',
        'Batch search releases for episodes',
        'Выполняет поиск релизов для набора выбранных серий тайтла.',
        'Executes a batch search across indexers for multiple selected episodes.',
    ),
    ('/api/v1/shows/{show_id}/search-season/{season_number}', 'POST'): (
        'Поиск релизов для целого сезона',
        'Search releases for season',
        'Выполняет поиск как сезонных паков (Season Packs), так и отдельных серий указанного сезона.',
        'Searches indexers for complete season packs as well as individual episodes of the specified season.',
    ),
    ('/api/v1/shows/{show_id}/season-splits', 'GET'): (
        'Список правил разделения сезонов (+Offset)',
        'List season split rules',
        'Возвращает правила виртуального разделения сезонов и смещения нумерации серий для аниме и сериалов.',
        'Returns season split and episode offset (+Offset) rules configured for anime or absolute-ordered shows.',
    ),
    ('/api/v1/shows/{show_id}/season-splits', 'POST'): (
        'Создать правило разделения сезона',
        'Create season split rule',
        'Создает новое правило смещения номеров эпизодов при сопоставлении абсолютной и сезонной нумерации.',
        'Creates a new episode numbering offset rule mapping absolute tracker releases to seasons.',
    ),
    ('/api/v1/shows/{show_id}/season-splits/{split_id}', 'DELETE'): (
        'Удалить правило разделения сезона',
        'Delete season split rule',
        'Удаляет правило смещения и разделения сезона из карточки тайтла.',
        'Deletes a season split and offset rule from the show.',
    ),
    ('/api/v1/shows/{show_id}/season-splits/{split_id}', 'PUT'): (
        'Обновить правило разделения сезона',
        'Update season split rule',
        'Изменяет диапазон серий, целевой сезон или величину смещения в правиле разделения сезона.',
        'Updates episode range, destination season, or offset count in an existing season split rule.',
    ),
    ('/api/v1/shows/{show_id}/seasons/{season_number}/monitor', 'PUT'): (
        'Переключить мониторинг конкретного сезона',
        'Toggle season monitoring',
        'Включает или выключает отслеживание и поиск серий для одного указанного сезона.',
        'Enables or disables tracking and wanted searches for a specific season.',
    ),
    ('/api/v1/shows/{show_id}/specials-import-status', 'GET'): (
        'Статус импорта специальных эпизодов (спешлов)',
        'Check specials import status',
        'Проверяет наличие неимпортированных или ожидающих ручной проверки файлов в папке Season 00 / Specials.',
        'Checks for pending or unmapped special episode files in the Season 00 / Specials folder.',
    ),
    ('/api/v1/shows/{show_id}/sync_disk', 'POST'): (
        'Синхронизировать файлы тайтла с диском',
        'Sync show files with disk',
        'Пересканирует директорию тайтла на диске и обновляет данные о файлах, размерах и кодеках в базе данных.',
        'Rescans the show storage directory and updates database records with on-disk files, sizes, and codecs.',
    ),
    ('/api/v1/shows/{show_id}/unaired/monitor', 'PUT'): (
        'Переключить мониторинг невышедших серий',
        'Toggle monitoring for unaired episodes',
        'Включает или выключает автоматический перевод будущих серий в статус WANTED при наступлении даты выхода.',
        'Controls whether future unaired episodes are automatically placed into WANTED status upon premiere.',
    ),
    ('/api/v1/shows/{show_id}/upgrade', 'POST'): (
        'Переключить режим апгрейда качества тайтла',
        'Toggle show quality upgrade',
        'Включает или выключает автоматический поиск более качественных версий для всех серий тайтла.',
        'Enables or disables automated quality upgrade searches across all episodes of the show.',
    ),
    ('/api/v1/shows/{show_id}/upload-cover', 'POST'): (
        'Загрузить пользовательскую обложку для тайтла',
        'Upload custom cover art',
        'Сохраняет переданный графический файл в качестве персональной обложки тайтла.',
        'Saves an uploaded image file as the custom poster artwork for the show.',
    ),
    ('/api/v1/stats', 'GET'): (
        'Сводная статистика медиатеки',
        'Get library summary statistics',
        'Возвращает количество фильмов, сериалов, серий, размер на диске и число активных загрузок.',
        'Returns totals for shows, movies, episodes, storage consumption, and active download tasks.',
    ),
    ('/api/v1/system/about', 'GET'): (
        'Информация о системе и среде выполнения',
        'System and environment info',
        'Возвращает версию Aliasarr, пути к данным, информацию об операционной системе, Python и утилитах.',
        'Returns Aliasarr version, data paths, host OS environment, Python runtime, and external utility status.',
    ),
    ('/api/v1/system/fix-media-permissions', 'POST'): (
        'Исправить права доступа ко всей медиатеке',
        'Fix media folder permissions globally',
        'Принудительно устанавливает права доступа (0777 для папок и 0666 для файлов) ко всем медиапапкам.',
        'Applies open read/write permissions (0777 for directories, 0666 for files) across all media folders.',
    ),
    ('/api/v1/tasks', 'GET'): (
        'Список и статус активных фоновых задач',
        'List status of active background tasks',
        'Возвращает перечень выполняющихся и завершенных фоновых задач планировщика и сервисных процессов.',
        'Returns the status, progress, and runtime details of running and scheduled background tasks.',
    ),
    ('/api/v1/tasks/clear-history', 'POST'): (
        'Очистить историю выполненных фоновых задач',
        'Clear background task history',
        'Удаляет записи о завершенных и ошибочных фоновых задачах из памяти планировщика.',
        'Clears records of completed and failed background jobs from the task manager history.',
    ),
    ('/api/v1/users', 'GET'): (
        'Список пользователей системы',
        'List system user accounts',
        'Возвращает перечень всех зарегистрированных учетных записей пользователей с ролями RBAC и статусами.',
        'Lists all registered user accounts along with their RBAC roles, permissions, and active status.',
    ),
    ('/api/v1/users', 'POST'): (
        'Создать нового пользователя',
        'Create new user account',
        'Регистрирует новую учетную запись пользователя с назначением роли и пароля.',
        'Registers a new user account with assigned role permissions and password.',
    ),
    ('/api/v1/users/{user_id}', 'DELETE'): (
        'Удалить учетную запись пользователя',
        'Delete user account',
        'Удаляет учетную запись пользователя из системы (за исключением владельца Owner).',
        'Deletes a user account from the system (prohibited for the system Owner).',
    ),
    ('/api/v1/users/{user_id}', 'GET'): (
        'Параметры учетной записи пользователя',
        'Get user account details',
        'Возвращает профиль пользователя, роль, статус двухфакторной защиты и персональный API-ключ.',
        'Returns user profile details: role, permissions, 2FA status, and assigned API key.',
    ),
    ('/api/v1/users/{user_id}', 'PUT'): (
        'Обновить учетную запись пользователя',
        'Update user account',
        'Обновляет логин, роль RBAC, активность и права доступа выбранного пользователя.',
        'Updates username, RBAC role, active flag, and access permissions for the user.',
    ),
    ('/api/v1/users/{user_id}/2fa/confirm', 'POST'): (
        'Административное подтверждение 2FA для пользователя',
        'Admin confirm 2FA for user',
        'Подтверждает и активирует 2FA TOTP для профиля пользователя.',
        'Validates TOTP code and permanently activates two-factor authentication for the user account.',
    ),
    ('/api/v1/users/{user_id}/2fa/reset', 'POST'): (
        'Сбросить 2FA для пользователя',
        'Admin reset 2FA for user',
        'Принудительно сбрасывает и отключает двухфакторную аутентификацию для профиля пользователя.',
        'Forces reset and removal of two-factor authentication from a user account.',
    ),
    ('/api/v1/users/{user_id}/2fa/setup', 'POST'): (
        'Административная инициализация 2FA для пользователя',
        'Admin setup 2FA for user',
        'Генерирует секретный ключ TOTP для настройки двухфакторной аутентификации пользователя администратором.',
        'Generates a new TOTP secret for setting up two-factor authentication on a user account.',
    ),
    ('/api/v1/users/{user_id}/avatar', 'POST'): (
        'Установить аватар пользователя',
        'Set user avatar',
        'Обновляет изображение профиля пользователя (поддерживаются форматы PNG, JPEG, WebP).',
        'Updates the profile avatar image for the user account.',
    ),
    ('/api/v1/users/{user_id}/regenerate-api-key', 'POST'): (
        'Перевыпустить персональный API-ключ пользователя',
        'Regenerate user personal API key',
        'Генерирует новый персональный API-ключ для выбранного пользователя администратором.',
        'Generates a new personal API key for the specified user account.',
    ),
    ('/api/v1/users/{user_id}/reset-password', 'POST'): (
        'Сбросить пароль пользователя',
        'Reset user password',
        'Устанавливает новый пароль для указанного пользователя администратором системы.',
        'Resets the password for a specified user account by an administrator.',
    ),
    ('/api/v1/users/{user_id}/revoke-api-key', 'DELETE'): (
        'Отозвать API-ключ пользователя',
        'Revoke user personal API key',
        'Аннулирует персональный API-ключ пользователя, отключая доступ к API по ключу.',
        'Revokes the personal API key of the user, disabling key-based API access.',
    ),
    ('/docs', 'GET'): (
        'Документация системы (редирект)',
        'System documentation (redirect)',
        'Перенаправляет клиента на страницу интерактивной базы знаний Wiki.',
        'Redirects client to the interactive Wiki knowledge base page.',
    ),
    ('/quality-guide', 'GET'): (
        'Интерактивное руководство по качеству',
        'Interactive Quality Profiles guide',
        'Отображает веб-страницу справочника профилей качества, релиз-групп и кастомных форматов.',
        'Renders the interactive web documentation page for quality profiles, release scoring, and formats.',
    ),
    ('/wiki', 'GET'): (
        'Интерактивная база знаний Aliasarr Wiki',
        'Aliasarr Wiki knowledge base',
        'Отображает официальную интерактивную веб-документацию и справочник системы Aliasarr.',
        'Renders the official interactive web documentation and knowledge base for Aliasarr.',
    ),
    ('/wiki.html', 'GET'): (
        'Интерактивная база знаний Wiki (прямая ссылка)',
        'Aliasarr Wiki documentation (direct URL)',
        'Прямая ссылка на веб-страницу интерактивной базы знаний Aliasarr Wiki.',
        'Direct URL serving the interactive Aliasarr Wiki documentation page.',
    ),
}

# Standard parameter localizations: param_name -> (ru_description, en_description)
COMMON_PARAM_DESCRIPTIONS: dict[str, tuple[str, str]] = {
    'show_id': ('Уникальный идентификатор тайтла', 'Unique title/show identifier'),
    'show_id_or_title': ('Идентификатор тайтла или название', 'Show identifier or title string'),
    'episode_id': ('Уникальный идентификатор серии', 'Unique episode identifier'),
    'season_number': ('Номер сезона', 'Season number'),
    'alias_id': ('Идентификатор поискового алиаса', 'Search alias identifier'),
    'split_id': ('Идентификатор правила разделения сезона (+Offset)', 'Season split rule identifier'),
    'indexer_id': ('Уникальный идентификатор торрент-индексатора', 'Unique torrent indexer identifier'),
    'client_id': ('Уникальный идентификатор торрент-клиента', 'Unique download client identifier'),
    'dc_id': ('Уникальный идентификатор торрент-клиента', 'Unique download client identifier'),
    'source_id': ('Идентификатор источника метаданных', 'Metadata source identifier'),
    'format_id': ('Идентификатор кастомного формата', 'Custom format identifier'),
    'profile_id': ('Идентификатор профиля качества', 'Quality profile identifier'),
    'item_id': ('Идентификатор элемента', 'Item identifier'),
    'user_id': ('Уникальный идентификатор пользователя', 'Unique user account identifier'),
    'session_id': ('Идентификатор сессии', 'Session token identifier'),
    'config_id': ('Идентификатор конфигурации', 'Configuration identifier'),
    'name': ('Имя файла или архива', 'File or archive name'),
    'torrent_hash': ('Инфохэш торрент-раздачи', 'Torrent infohash'),
    'collection_id': ('Идентификатор коллекции фильмов TMDb', 'TMDb movie collection identifier'),
    'page': ('Номер страницы для пагинации', 'Page number for pagination'),
    'limit': ('Количество записей на страницу', 'Number of records per page'),
    'query': ('Поисковый запрос', 'Search query'),
    'search': ('Поисковый запрос', 'Search query'),
    'q': ('Строка поиска', 'Search string'),
    'lang': ('Языковой код (ru или en)', 'Language code (ru or en)'),
    'force_refresh': ('Принудительно обновить данные из источника', 'Force refresh data from source'),
    'content_type': ('Тип медиаконтента (movie, show, anime)', 'Media content type (movie, show, anime)'),
}

# Response status code descriptions
RESPONSES_RU: dict[str, str] = {
    "200": "Успешный ответ",
    "201": "Успешно создано",
    "204": "Успешно обработано (нет содержимого)",
    "400": "Ошибка валидации параметров запроса",
    "401": "Требуется авторизация (неверный API-ключ или сессия)",
    "403": "Доступ запрещен (недостаточно прав RBAC)",
    "404": "Запрашиваемый ресурс не найден",
    "409": "Конфликт состояния ресурса",
    "422": "Некорректные данные запроса (Unprocessable Entity)",
    "429": "Превышен лимит запросов (Rate Limiter)",
    "500": "Внутренняя ошибка сервера",
}

RESPONSES_EN: dict[str, str] = {
    "200": "Successful response",
    "201": "Successfully created",
    "204": "Successfully processed (no content)",
    "400": "Validation or parameter error",
    "401": "Authentication required (missing or invalid API key/session)",
    "403": "Access forbidden (insufficient RBAC permissions)",
    "404": "Requested resource not found",
    "409": "Conflict with current resource state",
    "422": "Unprocessable entity (invalid request payload)",
    "429": "Rate limit exceeded",
    "500": "Internal server error",
}
